name: Build Qt6 Windows
on:
    workflow_dispatch:
        inputs:
            tag:
                description: 'Build tag'
                required: true
                type: string
                default: '6.6.0'
            mode:
                description: 'Build Target Mode'
                required: true
                type: choice
                options:
                - release
                - debug
                - debug-and-release
            arch:
                description: 'Build arch'
                type: choice
                options:
                  - x64
                  - x86
                required: true
            src_dir:
                description: 'Download Qt Source Directory'
                required: true
                type: string
                default: 'D:/Qt6/qtbase'
            install_dir:
                description: 'Install Qt Libs Directory'
                required: true
                type: string
                default: 'C:/Local/Qt6'

jobs:
    build:
        name: Build
        runs-on: windows-2019

        steps:
            - name: Setup Environment
              working-directory: "C:/"
              shell: pwsh
              run: |
                mkdir -p ${{ inputs.src_dir }}
                mkdir -p ${{ inputs.install_dir }}
                choco install -y --no-progress wget unzip

            - name: Download Qt
              working-directory: "${{ inputs.src_dir }}"
              shell: pwsh
              run: |
                wget -qq https://github.com/qt/qtbase/archive/refs/tags/v${{ inputs.tag }}.zip
                7z x v${{ inputs.tag }}.zip -y

            - name: Set up Visual Studio shell on Windows
              uses: egor-tensin/vs-shell@v2
              with:
                  arch: ${{ inputs.arch }}

            - name: Build
              working-directory: "${{ inputs.src_dir }}/qtbase-${{ inputs.tag }}"
              shell: pwsh
              run: |
                cd ${{ inputs.src_dir }}/qtbase-${{ inputs.tag }}
                .\configure -prefix "${{ inputs.install_dir }}" -static -static-runtime -${{ inputs.mode }} -confirm-license -opensource ${{ inputs.mode == 'debug' && '' || '-optimize-size' }} -c++std c++20
                cmake --build . -j
                cmake --install .

            - name: Package output files
              working-directory: "D:/"
              shell: pwsh
              run: |
                7z a -t7z qt-${{inputs.tag}}-${{inputs.arch}}-${{inputs.mode}}-static.7z "${{ inputs.install_dir }}/*"

            - uses: actions/upload-artifact@v3
              with:
                  path: "D:/qt-${{inputs.tag}}-${{inputs.arch}}-${{inputs.mode}}-static.7z"
