name: Build Qt6 Windows
on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Build version'
                required: true
                type: string
                default: 'dev'
            configure-args:
                description: 'Build args'
                required: true
                type: string
            modules:
                description: 'Build modules'
                required: true
                type: string
                default: 'default'
            arch:
                description: 'Build arch'
                type: choice
                options:
                  - x86
                  - x64
                required: true
jobs:
    build:
        name: Build
        runs-on: windows-2019

        steps:
            - name: Set up Visual Studio shell on Windows
              uses: egor-tensin/vs-shell@v2
              with:
                  arch: ${{ inputs.arch }}
            
            - name: Setup Environment
              working-directory: "C:/"
              shell: pwsh
              run: |
                mkdir -p C:/Local/qt6-source
            
            - name: Download Qt
              working-directory: "C:/Local/qt6-source"
              shell: pwsh
              run: | 
                git clone https://github.com/qt/qtbase.git -b v${{ inputs.version }} C:/Local/qt6-source
                cd C:/Local/qt6-source

            - name: Build
              working-directory: "C:/Local/qt6-source"
              shell: pwsh
              run: |
                mkdir build
                cd build
                ..\configure.bat -prefix "C:/Local/Qt6" -static -static-runtime -debug-and-release -confirm-license -opensource -optimize-size -c++std c++20
                cmake --build . -j
                cmake --install .

            - name: Package output files
              working-directory: "D:/"
              shell: pwsh
              run: |
                7z a -t7z qt-${{inputs.version}}-${{inputs.arch}}-static.7z "C:\Local\Qt6\*"

            - uses: actions/upload-artifact@v3
              with:
                  path: "D:/qt-${{inputs.version}}-${{inputs.arch}}-static.7z"
